name: NuGet Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - uses: dotnet/nbgv@master
      with:
        setAllVars: true

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: | # | character makes the "run" property multi-line, so we can put multiple commands in the same step
        mkdir __out
        dotnet pack -c Release -o __out --no-restore -p:RepositoryBranch=master -p:ContinuousIntegrationBuild=true /p:PublicRelease=true
        dotnet nuget push -s "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_TOKEN}}
        rm -rf __out
